title: Gate # name of the site
author: Ev # name of site's author
email: bossy-signet.4s@icloud.com # email of site's author
url: edouardmass.github.io # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  A minimal, optimized, lightweight design for static sites.

git_repo: edouardmass/edouardmass.github.io

permalink: /:slug

favicon: favicon.svg # name+extension of favicon (which must be put on the root folder)
# goat_counter: yree # put your GoatCounter name if you want to use GoatCounter analytics

# theme: mold # if you are using GitHub Pages, change it to remote_theme: yree/mold
remote_theme: yree/mold

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  color_emoji: false # set to true for color emojis

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
